import json

csc_config={
    "samples":["SingleMuon"],
    "year":2017,
    "main_gdir":"DQMData/Run {0}/CSC/Run summary/CSCOfflineMonitor/",
    "hists":[
            {
                "path":"Occupancy/hORecHits",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.0,
                "min_entries":100000,
                "always_draw":False
            },
            {
                "path":"Occupancy/hOSegments",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.0,
                "min_entries":100000,
                "always_draw":False
            },
            {
                "path":"Occupancy/hOStrips",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.0,
                "min_entries":100000,
                "always_draw":False
            },
            {
                "path":"Occupancy/hOWires",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.0,
                "min_entries":100000,
                "always_draw":False
            },
            {
                "path":"recHits/hRHGlobal*",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.0,
                "min_entries":100000,
                "always_draw":False
            },
            {
                "path":"recHits/hRHnrechits",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.09,
                "min_entries":100000,
                "always_draw":True
            },
            {
                "path":"Digis/hWireTBin_*",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.09,
                "min_entries":100000,
                "always_draw":False
            },
            {
                "path":"Digis/hStripNFired",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.09,
                "min_entries":100000,
                "always_draw":True
            },
            {
                "path":"Digis/hWirenGroupsTotal",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.09,
                "min_entries":100000,
                "always_draw":True
            },
            {
                "path":"Segments/hSnhits*",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.09,
                "min_entries":100000,
                "always_draw":False
            },
            {
                "path":"Segments/hSnSegments",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.09,
                "min_entries":100000,
                "always_draw":True
            },
            {
                "path":"Segments/hSnhits",
                "name_out":"",
                "chi2_cut":500,
                "pull_cap":25,
                "pull_cut":20,
                "ks_cut":0.09,
                "min_entries":100000,
                "always_draw":True
            }
            ],
}

with open("configs.json", "w") as f:
    json.dump(csc_config, f, sort_keys = True, indent = 4, separators = (',',':'))
